version: 2.1

defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-29
  environment:
    JVM_OPTS: -Xmx3g
  resource_class: large

general_cache_key: &general_cache_key
  key: jars-{{ .Environment.CIRCLE_CACHE_VER }}-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/code

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *general_cache_key
      - run: yes | sdkmanager --licenses || exit 0
      - run: yes | sdkmanager --update || exit 0
      - run:
          name: Copy gradle.properties for CI
          command: mkdir -p ~/.gradle ; cp .circleci/ci-gradle.properties ~/.gradle/gradle.properties
      - run:
          name: Run Tests
          command: ./gradlew jacocoReport
      - run:
          name: Upload Code Coverage
          command: bash <(curl -s https://codecov.io/bash) -t a3a5e628-25f2-4588-8a59-a16647ede519 -f build/reports/jacoco/jacocoReport/jacocoReport.xml
      - save_cache:
          paths:
            - ~/.gradle
          <<: *general_cache_key
      - store_test_results:
          path: core/build/test-results
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - persist_to_workspace:
          root: ~/code
          paths:
            - .

  deploy_to_google_play:
    <<: *defaults
    steps:
      - *attach_workspace
      - restore_cache:
          <<: *general_cache_key
      - run:
          name: Deploy to Google Play
          command: |
            if [[ "${CIRCLE_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Deploy to Google Play"
              ./gradlew clean bundleRelease publishReleaseBundle
            fi

  deploy_to_deploygate:
    <<: *defaults
    steps:
      - *attach_workspace
      - restore_cache:
          <<: *general_cache_key
      - run:
          name: Deploy to Deploygate
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ ^release.*$ ]]; then
              echo "Deploy to DeployGate"
              ./gradlew clean uploadDeployGateDebug uploadDeployGateQa uploadDeployGateBeta
            fi

workflows:
  version: 2.1

  build_and_deploy_to_deploygate:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - deploy_to_deploygate:
          requires:
            - build
          filters:
            branches:
              only: /^release.*$/

  deploy_and_deploy_to_google_play:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
      - deploy_to_google_play:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
