version: 2

defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-29
  environment:
    JVM_OPTS: -Xmx3200m
on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: sudo chmod +x ./gradlew
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build apk
          command: ./gradlew :app:assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/app-debug.apk
          destination: app-debug.apk

  apply_ktlint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code
      - run:
          with:
            ref: ${{ github.event.pull_request.head.ref }}
          name: Apply ktlint format
          command: ./gradlew ktlintFormat
      - run:
          name: Commit changes
          shell: /bin/bash
          command: |
            git config --local user.email "duong.hoang@nokasoft.com"
            git config --local user.name "noka-bot"
            git commit -am "Apply ktlint Format"
            git push https://nokaduonghb:${DANGER_GITHUB_API_TOKEN}@github.com/nokaduonghb/BitriseCIDemo.git
            exit 0

workflows:
  version: 2
  build_and_apply_ktlint:
    jobs:
      - build
      - apply_ktlint:
          requires:
            - build