version: 2

defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-29
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  apply_ktlint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Apply ktlint format
          command: ./gradlew ktlintFormat
      - run:
          name: Commit changes
          shell: bash +e {0}
          command: |
            git config --local user.email "noka-bot@noka.co"
            git config --local user.name "noka-bot"
            git commit -am "Apply ktlint Format" && git push origin HEAD
            exit 0

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - apply_ktlint