version: 2

defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-29
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  apply_ktlint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: sudo chmod +x ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Apply ktlint format
          command: ./gradlew ktlintFormat
      - run: '[ ! -z $DANGER_GITHUB_API_TOKEN ]'
      - run:
          name: Commit changes
          command: |
            git config --local user.email "duong.hoang@nokasoft.com"
            git config --local user.name "noka-bot"
            git commit -am "Apply ktlint Format"
            git push -q https://${DANGER_GITHUB_API_TOKEN}@github.com/nokaduonghb/BitriseCIDemo.git origin HEAD
            exit 0

workflows:
  version: 2
  build_and_apply_ktlint:
    jobs:
      - apply_ktlint