# PR がレビュー可能になったら Ktlint を適用する
name: Ktlint Check & Apply Ktlint format & Commit changes

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  ktlint-danger-apply:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-ruby-${{ runner.os }}-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: bundle-ruby-${{ runner.os }}-${{ hashFiles('.ruby-version') }}-
      - name: install gem
        run: |
          bundle config path vendor/bundle
          bundle install
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-cache-
      - uses: actions/cache@v1
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle-project-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-project-
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: ktlint
        run: ./gradlew ktlintCheck
      - name: Danger
        env:
          DANGER_GITHUB_API_TOKEN:  ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: bundle exec danger

